spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/h2db/kakao1
    username: sa
    password:
      driver-class-name: org.h2.Driver

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true

#logging:
#  config:
#    classpath:
#      log4j2-local.xml
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace